Repository OptiCorp/inventory-app, pull requests merged in 2024-02, with the labels that each got.

#305 fix: issue with label/option in Autocomplete in category
  src/components/AddItemFormFields/Category/Category.tsx
Labels: fix

#299 refactor: snackbar from hook to component
  src/App.tsx
  src/components/Snackbar/Snackbar.stories.tsx
  src/components/Snackbar/Snackbar.tsx
  src/contexts/AppContext.tsx
  src/hooks/index.ts
  src/pages/addItem/hooks/itemValidator.ts
  src/pages/itemDetails/itemInfo/ItemInfo.tsx
  src/pages/list/MakeList.tsx
  src/pages/listDetails/ListDetails.tsx
  src/pages/listDetails/ListHeader.tsx
  src/pages/listDetails/phone/AddMore.tsx
  src/pages/listDetails/phone/list/PhoneList.tsx
Labels: refactor, feat

#309 fix: category
  src/components/AddItemFormFields/Category/Category.tsx
Labels: fix

#316 fix: addItem function and reset form after success
  src/pages/addItem/Index.tsx
  src/pages/addItem/hooks/useAddItemForm.ts
  src/pages/addItem/template/Template.tsx
Labels: fix, feat

#318 added back hamburger menu to phone
  src/components/TopBar/HamburgerMenu/HamburgerMenu.tsx
  src/components/TopBar/ResponsiveAppBar.tsx
  src/components/TopBar/styles.ts
  src/pages/list/styles.ts
  src/pages/search/styles.ts
Labels: fix, feat

#324 refactor: update url stucture for item page
  src/App.tsx
  src/components/ItemCard/ItemCard.tsx
  src/components/ItemCard/SearchInfo/SearchInfo.tsx
  src/components/ItemCard/SearchInfoCompact/SearchInfoCompact.tsx
  src/components/ResultSearchCard/ResultSearchCard.tsx
  src/pages/itemDetails/Index.tsx
  src/pages/itemDetails/hierarchy/ChildItemSelector.tsx
  src/pages/itemDetails/hierarchy/ParentItemSelector.tsx
Labels: refactor

#353 removal of query devtools
  src/main.tsx
Labels: refactor, quick

#354 fix
  src/components/AddItemFormFields/SerialNumbers/SerialNumbers.tsx
  src/components/AddItemFormFields/WpIds/WpIds.tsx
  src/pages/addItem/Index.tsx
  src/pages/addItem/addItemForm/FormContent.tsx
  src/pages/addItem/batch/BatchForm.tsx
  src/pages/addItem/batch/hooks/useBatchForm.tsx
  src/pages/addItem/hooks/useAddItemForm.ts
  src/pages/itemDetails/itemInfo/ItemInfo.tsx
Labels: fix

#355 fix: missing name log entry
  src/components/ItemDetails/Entry.tsx
Labels: fix, quick
